# compose file for festivals-website
version: '1'

services:

  identity:
    restart: always
    image: my/festivals-website
    container_name: festivals-website
    hostname: festivals-website
    networks:
      festivals_backend:
        aliases:
          - website.festivals-gateway
 #       ipv4_address: 172.20.0.1
      
networks:
  festivals_backend:
    external: true
    name: festivals-network
